=== beltsonata/idonmapper/idonmapper_stable/idonmapper/idon-map.dtd
<!ELEMENT idon-map (map-name, cell-size, idons, suggestions, view-position)>
<!ELEMENT map-name (#PCDATA)>
<!ELEMENT cell-size (#PCDATA)>
<!ELEMENT idons (idon*)>
<!ELEMENT idon (coord,idea,color,size)>
<!ELEMENT coord (x-coord,y-coord)>
<!ELEMENT x-coord (#PCDATA)>
<!ELEMENT y-coord (#PCDATA)>
<!ELEMENT idea (#PCDATA)>
<!ELEMENT color (red,green,blue)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT suggestions (suggestion*)>
<!ELEMENT suggestion (#PCDATA)>
<!ELEMENT view-position (height,width,x-pos,y-pos)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT x-pos (#PCDATA)>
<!ELEMENT y-pos (#PCDATA)>

=== beltsonata/idonmapper/idonmapper_stable/idonmapper/xmlReaderTest.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE idon-map SYSTEM "idon-map.dtd">
<idon-map> 
<map-name>Xml Reader Test Map</map-name>
<cell-size>55</cell-size>
    <idons>
        <idon>
            <coord><x-coord>78</x-coord><y-coord>77</y-coord></coord>    
            <idea>Is this thing on?</idea>    
            <color><red>0</red><green>255</green><blue>255</blue></color>
        </idon>
        <idon>
            <coord><x-coord>79</x-coord><y-coord>77</y-coord></coord>    
            <idea>Yes it is</idea>    
            <color><red>0</red><green>255</green><blue>255</blue></color>
        </idon>
    </idons>
    <suggestions>
        <suggestion>blah1</suggestion>
        <suggestion>blah2</suggestion>
    </suggestions>
    <view-position>
        <height>501</height><width>762</width><x-pos>7049</x-pos><y-pos>6105</y-pos>
    </view-position>
</idon-map>

=== beltsonata/idonmapper/idonmapper_stable/idonmapper/xmlReaderTest2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE idon-map SYSTEM "idon-map.dtd">
<idon-map>
<map-name>xmlReaderTest2.xml</map-name>
<cell-size>55.0</cell-size>
<idons>
<idon>
<coord>
<x-coord>79</x-coord>
<y-coord>79</y-coord>
</coord>
<idea>YES IT IS</idea>
<color>
<red>0</red>
<green>255</green>
<blue>255</blue>
</color>
</idon>
<idon>
<coord>
<x-coord>78</x-coord>
<y-coord>78</y-coord>
</coord>
<idea>IS THIS THING ON?</idea>
<color>
<red>0</red>
<green>255</green>
<blue>255</blue>
</color>
</idon>
</idons>
<suggestions>
<suggestion>blah1</suggestion>
<suggestion>blah2</suggestion>
</suggestions>
<view-position>
<height>480</height>
<width>762</width>
<x-pos>7049</x-pos>
<y-pos>6135</y-pos>
</view-position>
</idon-map>
